#!/usr/bin/env python
"""Bootstrap the local artifact folder for a `rootcause` investigation.

Pure local scaffolding for the `/rootcause` skill: no network, no Jira API
(all Jira I/O stays in the sibling `jira` skill's jira.py). Given a ticket key
it creates the artifact directory tree under the VTune build repo and seeds
NOTES.md / ROOTCAUSE.md skeletons, then prints the paths the skill needs.

  rc_bootstrap.py <KEY> [--repo DIR]

Output (parse-friendly, one key=value per line):
  ARTIFACT_DIR=<abs path to jira_artifacts/<key_lower>>
  ATTACHMENTS_DIR=<abs path to .../attachments>
  DOWNLOAD_DIR_ARG=<the value to pass to `jira.py download --dir`>
  CONFLUENCE_DIR=<abs path to .../confluence>
  CONFLUENCE_DIR_ARG=<the value to pass to `confluence.py download --dir`>
  NOTES=<abs path to NOTES.md>
  REPORT=<abs path to ROOTCAUSE.md>

Existing NOTES.md / ROOTCAUSE.md are never clobbered. Exit 0 on success,
2 on a usage error.
"""

import argparse
import os
import re
import sys

# The VTune build repo. Resolution order (so the skill is not hard-wired to one
# checkout or one user): explicit --repo > VTUNE_BUILD_DIR env > CLAUDE_PROJECT_DIR
# (the workspace root Claude Code was opened in — normally the vtune_build checkout)
# > the current working directory.
DEFAULT_REPO = (
    os.environ.get("VTUNE_BUILD_DIR")
    or os.environ.get("CLAUDE_PROJECT_DIR")
    or os.getcwd())

KEY_RE = re.compile(r"^[A-Za-z][A-Za-z0-9]*-\d+$")

NOTES_TEMPLATE = """\
# {key_upper} — fetched notes

_Raw material pulled from Jira. Written by the /rootcause skill. Do not put
secrets (e.g. JIRA_TOKEN) here._

## Ticket
<!-- summary, type, priority, status, components, labels, assignee, reporter,
     affected version — from `jira.py view {key_upper}` -->

## Build-tracking (BT)
<!-- Fill ONLY when the summary starts with [BT]. "Found in build" =
     customfield_14617; stream = the [BT] [<stream>] summary token. Run
     rc_bt.py <build> --stream <stream> and record:
       Found in build: <n>   Resolved tag: <#build+stream+...>
       Baseline tag: <#prev+...>
     then the bumped-component table (| component | old | new |). The regression
     is almost certainly one of these components or a transitive dependent.
     Note any build-number discrepancy between the field and the description. -->

## Description
<!-- from `jira.py view {key_upper}` -->

## Comments digest
<!-- from `jira.py comments {key_upper} --limit 50` -->

## Attachments
<!-- inventory: filename / size / type — from `jira.py attachments {key_upper}`;
     files downloaded into ./attachments/ -->

## Linked Confluence pages
<!-- Fill for each wiki.ith.intel.com page linked from the ticket. Use the
     confluence skill: `confluence.py view "<url>"` to read, `confluence.py
     download "<url>" --all --dir ./confluence` to pull its docs, `confluence.py
     links "<url>"` for further links. Per page record:
       Title / URL — short digest — docs saved under ./confluence/ -->

## Support matrix
<!-- Digest of the Analyzers Support Matrix (confluence pageId 2698724254) or the
     perfconfigs4 backup. Record VTune's per-OS tags (P1/P2/P3/DROPPED) and
     per-CPU tags (Public/NDA/Internal/absent), and — once the collection platform
     is known — whether the platform the failing result was collected on is
     in-support, reactive-only (P3), or OUT OF SUPPORT (dropped/absent OS or
     microarch). Backup source: vcs/perfconfigs4 scripts/maps.py
     (_PLATFORM_FILE_NAME = abbrev<->PMU codename bridge) + include/pmu_common.xsl
     (exsl:ctx('PMU')='<codename>' switches; absent = intentionally de-supported,
     cf. VASP-32463). -->

## Extracted signals
<!-- stack traces, crash signatures, module/symbol names, repro steps -->
"""

REPORT_TEMPLATE = """\
# {key_upper} — root-cause report

_Generated by the /rootcause skill. Ranked hypotheses; not a final verdict._

## Ticket summary

## Reproduction / inputs

## Support-matrix status
<!-- Was the failing result collected on a supported platform? State the OS
     (name+version) and microarch/CPU of the failing run, and its support tag from
     the Analyzers Support Matrix (P1/P2/P3 or DROPPED for OS; Public/NDA/Internal
     or absent for CPU). If the platform is OUT OF SUPPORT (dropped/absent OS or
     microarch), that likely reclassifies the ticket from a product regression to
     out-of-support / test-infra — say so. If in-support, say "in support (Pn)".
     "unknown — collection platform not determinable" if the evidence doesn't pin
     it. Source: confluence pageId 2698724254; backup vcs/perfconfigs4. -->

## Affected component(s) & owners
<!-- ranked vcs/<comp> candidates + CODEOWNERS -->

## Evidence
<!-- for a [BT] ticket, cite the bumped-component list from rc_bt.py (found
     build → tag → SConstruct diff) as the primary suspect set -->

## Root-cause hypothesis (+confidence)

## Alternatives considered

## Fix applied (if any)
<!-- changed components, reference to fix.diff, build/test result -->

## Suggested next verification

## Open questions

## Permissions I still lack for full autonomy
<!-- each deferred action + the exact tool pattern that would unlock it, or
     "none — the granted set was sufficient" -->
"""


def _die(msg):
    sys.stderr.write("ERROR: " + msg + "\n")
    raise SystemExit(2)


def main(argv=None):
    # Match jira.py: force UTF-8 so a cp1252 Windows console doesn't mangle
    # non-ASCII paths/output.
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8")
        except (AttributeError, ValueError):
            pass

    p = argparse.ArgumentParser(
        prog="rc_bootstrap.py",
        description="Create the artifact folder + note templates for a rootcause run.")
    p.add_argument("key", help="ticket key, e.g. VASP-32909 (any PREFIX-NNNNN)")
    p.add_argument("--repo", default=DEFAULT_REPO,
                   help="VTune build repo root (default: %(default)s)")
    args = p.parse_args(argv)

    key = args.key.strip()
    if not KEY_RE.match(key):
        _die("bad ticket key {0!r}; expected PREFIX-NNNNN (e.g. VASP-32909).".format(key))
    key_upper = key.upper()
    key_lower = key.lower()

    repo = os.path.abspath(args.repo)
    if not os.path.isdir(repo):
        _die("repo dir not found: {0} (set --repo or VTUNE_BUILD_DIR).".format(repo))

    artifact_dir = os.path.join(repo, "jira_artifacts", key_lower)
    attachments_dir = os.path.join(artifact_dir, "attachments")
    confluence_dir = os.path.join(artifact_dir, "confluence")
    os.makedirs(attachments_dir, exist_ok=True)
    os.makedirs(confluence_dir, exist_ok=True)

    notes = os.path.join(artifact_dir, "NOTES.md")
    report = os.path.join(artifact_dir, "ROOTCAUSE.md")
    if not os.path.exists(notes):
        with open(notes, "w", encoding="utf-8") as fh:
            fh.write(NOTES_TEMPLATE.format(key_upper=key_upper))
    if not os.path.exists(report):
        with open(report, "w", encoding="utf-8") as fh:
            fh.write(REPORT_TEMPLATE.format(key_upper=key_upper))

    print("ARTIFACT_DIR={0}".format(artifact_dir))
    print("ATTACHMENTS_DIR={0}".format(attachments_dir))
    print("CONFLUENCE_DIR={0}".format(confluence_dir))
    # Forward slashes: friendliest for the quoted --dir arg the skill passes on.
    print("DOWNLOAD_DIR_ARG={0}".format(attachments_dir.replace("\\", "/")))
    print("CONFLUENCE_DIR_ARG={0}".format(confluence_dir.replace("\\", "/")))
    print("NOTES={0}".format(notes))
    print("REPORT={0}".format(report))


if __name__ == "__main__":
    main()
