#!/usr/bin/env python
"""Bootstrap the local artifact folder for an `implement-feature` run.

Pure local scaffolding for the `/implement-feature` skill: no network, no Jira
API (all Jira I/O stays in the sibling `jira` skill's jira.py). Given a request
-- either a ticket key (PREFIX-NNNNN) or a free-text feature description -- it
creates the artifact directory tree under the VTune build repo and seeds
NOTES.md / IMPLEMENTATION.md skeletons, then prints the paths the skill needs.

  if_bootstrap.py <SLUG> [--slug NAME] [--repo DIR]

<SLUG> is classified:
  * matches PREFIX-NNNNN  -> ticket mode; folder name is the key lower-cased.
  * anything else         -> free-text mode; folder name is a deterministic
                             sanitized slug of the text (override with --slug).

Output (parse-friendly, one key=value per line):
  INPUT_MODE=ticket|freetext
  ARTIFACT_DIR=<abs path to jira_artifacts/<folder>>
  ATTACHMENTS_DIR=<abs path to .../attachments>
  DOWNLOAD_DIR_ARG=<the value to pass to `jira.py download --dir`>
  CONFLUENCE_DIR=<abs path to .../confluence>
  CONFLUENCE_DIR_ARG=<the value to pass to `confluence.py download --dir`>
  NOTES=<abs path to NOTES.md>
  REPORT=<abs path to IMPLEMENTATION.md>

Existing NOTES.md / IMPLEMENTATION.md are never clobbered. Exit 0 on success,
2 on a usage error.
"""

import argparse
import os
import re
import sys

# The VTune build repo. Resolution order (so the skill is not hard-wired to one
# checkout or one user): explicit --repo > VTUNE_BUILD_DIR env > CLAUDE_PROJECT_DIR
# (the workspace root Claude Code was opened in — normally the vtune_build checkout)
# > the current working directory.
DEFAULT_REPO = (
    os.environ.get("VTUNE_BUILD_DIR")
    or os.environ.get("CLAUDE_PROJECT_DIR")
    or os.getcwd())

KEY_RE = re.compile(r"^[A-Za-z][A-Za-z0-9]*-\d+$")

# Free-text folder slug: keep it short, filesystem-safe, and deterministic so
# re-running with the same description reuses the same artifact folder (no
# timestamp/random entropy).
_SLUG_MAX = 60

NOTES_TEMPLATE = """\
# {title} -- fetched notes

_Raw material for the feature. Written by the /implement-feature skill. Do not
put secrets (e.g. JIRA_TOKEN) here._

## Feature request
<!-- In ticket mode: the summary + description from `jira.py view KEY_UPPER`.
     In free-text mode: the user's written request, captured verbatim -- this
     is the source of truth when there is no ticket. -->

## Requirements & acceptance criteria
<!-- Concrete, testable behaviors the feature must satisfy. Pull explicit
     acceptance criteria from the ticket/description; make implicit ones
     explicit. Each becomes a test case later. -->

## Description
<!-- Full ticket description (ticket mode) or expanded request (free-text). -->

## Comments digest
<!-- Ticket mode only: design discussion / clarifications from
     `jira.py comments KEY_UPPER --limit 50`. -->

## Attachments
<!-- Ticket mode only: inventory (filename / size / type) from
     `jira.py attachments KEY_UPPER`; files downloaded into ./attachments/ -->

## Linked Confluence pages
<!-- Fill for each wiki.ith.intel.com page linked from the ticket or pasted in
     the free-text request. Use the confluence skill: `confluence.py view
     "<url>"` to read, `confluence.py download "<url>" --all --dir ./confluence`
     to pull its docs, `confluence.py links "<url>"` for further links. Per page
     record: Title / URL -- short digest -- docs saved under ./confluence/ -->

## Relevant existing code / patterns to reuse
<!-- vcs/<comp> components, interfaces, and utilities the feature should build
     on rather than reinvent -- filled during the Phase B design workflow. -->
"""

REPORT_TEMPLATE = """\
# {title} -- implementation doc

_Generated by the /implement-feature skill. Design + plan; the plan is approved
by the user before any code is written._

## Feature summary

## Requirements & acceptance criteria

## Design
<!-- target vcs/<comp> component(s) + CODEOWNERS; existing interfaces/APIs to
     use or extend; files to create/modify; .parts dependency changes. -->

## Test strategy
<!-- unit-preferred: exact framework (gtest/TUT/Python) + test-file path +
     each acceptance criterion -> test case. Integration (perfdqtests/perftests)
     only if the behavior can't be unit-tested; note it may not run locally. -->

## Implementation applied (if any)
<!-- changed components, reference to impl.diff, build result -->

## Test results
<!-- tests added, pass/fail (cite logs/run_utest.<comp>.*.log), or why the
     behavior was not unit-testable and what was done instead -->

## Open items
<!-- unresolved ambiguities, missing/red tests, follow-ups -->

## PR status
<!-- branch, draft PR URL, Copilot review state / loop position (if opened) -->

## Permissions I still lack for full autonomy
<!-- each deferred action + the exact tool pattern that would unlock it, or
     "none -- the granted set was sufficient" -->
"""


def _die(msg):
    sys.stderr.write("ERROR: " + msg + "\n")
    raise SystemExit(2)


def _slugify(text):
    """Deterministic, filesystem-safe folder slug from free text.

    lowercase -> non-alphanumerics collapse to single '_' -> trim '_' -> cap
    length. No timestamp/hash so repeated runs on the same text are idempotent.
    """
    s = text.strip().lower()
    s = re.sub(r"[^a-z0-9]+", "_", s)
    s = s.strip("_")
    if len(s) > _SLUG_MAX:
        s = s[:_SLUG_MAX].rstrip("_")
    return s or "feature"


def main(argv=None):
    # Match jira.py: force UTF-8 so a cp1252 Windows console doesn't mangle
    # non-ASCII paths/output.
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8")
        except (AttributeError, ValueError):
            pass

    p = argparse.ArgumentParser(
        prog="if_bootstrap.py",
        description="Create the artifact folder + note templates for an "
                    "implement-feature run.")
    p.add_argument("slug", help="ticket key (e.g. VASP-32909) OR a free-text "
                                 "feature description")
    p.add_argument("--slug", dest="slug_override", default=None,
                   help="explicit folder slug for free-text mode (ignored in "
                        "ticket mode)")
    p.add_argument("--repo", default=DEFAULT_REPO,
                   help="VTune build repo root (default: %(default)s)")
    args = p.parse_args(argv)

    raw = args.slug.strip()
    if not raw:
        _die("empty request; pass a ticket key (PREFIX-NNNNN) or a description.")

    if KEY_RE.match(raw):
        mode = "ticket"
        key_upper = raw.upper()
        folder = raw.lower()
        title = key_upper
    else:
        mode = "freetext"
        folder = _slugify(args.slug_override or raw)
        # Title shown in the note headers: a short, readable form of the request.
        title = raw if len(raw) <= 80 else raw[:77].rstrip() + "..."

    repo = os.path.abspath(args.repo)
    if not os.path.isdir(repo):
        _die("repo dir not found: {0} (set --repo or VTUNE_BUILD_DIR).".format(repo))

    artifact_dir = os.path.join(repo, "jira_artifacts", folder)
    attachments_dir = os.path.join(artifact_dir, "attachments")
    confluence_dir = os.path.join(artifact_dir, "confluence")
    os.makedirs(attachments_dir, exist_ok=True)
    os.makedirs(confluence_dir, exist_ok=True)

    notes = os.path.join(artifact_dir, "NOTES.md")
    report = os.path.join(artifact_dir, "IMPLEMENTATION.md")
    if not os.path.exists(notes):
        with open(notes, "w", encoding="utf-8") as fh:
            fh.write(NOTES_TEMPLATE.format(title=title))
    if not os.path.exists(report):
        with open(report, "w", encoding="utf-8") as fh:
            fh.write(REPORT_TEMPLATE.format(title=title))

    print("INPUT_MODE={0}".format(mode))
    print("ARTIFACT_DIR={0}".format(artifact_dir))
    print("ATTACHMENTS_DIR={0}".format(attachments_dir))
    print("CONFLUENCE_DIR={0}".format(confluence_dir))
    # Forward slashes: friendliest for the quoted --dir arg the skill passes on.
    print("DOWNLOAD_DIR_ARG={0}".format(attachments_dir.replace("\\", "/")))
    print("CONFLUENCE_DIR_ARG={0}".format(confluence_dir.replace("\\", "/")))
    print("NOTES={0}".format(notes))
    print("REPORT={0}".format(report))


if __name__ == "__main__":
    main()
